### ISSUE TITLE
Awesome extension! The White Text is hard to see with the new 2019 logo.

### ISSUE THREAD

**Issue by jbeacham** [DreamTeamMobile/VS4Mac.SolutionName#2]
The White Text is hard to see with the new 2019 logo. Wondering if black would be better, but then hard to see behind the logo. Not sure the best answer.

**Comment by alexsorokoletov** [comment]
@jbeacham thanks for the feedback!
Good point about the 2019 logo, need to check that and see if they also have something better now that we can use (I know the "New instance" menu was added")
